### ISSUE TITLE
question about mixture

### ISSUE THREAD

**Issue by puallee** [lucidrains/mixture-of-attention#1]
>>> import  mixture_of_attention
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/mixture_of_attention/__init__.py", line 1, in <module>
    from mixture_of_attention.mixture_of_attention import (
  File "/usr/local/lib/python3.9/site-packages/mixture_of_attention/mixture_of_attention.py", line 11, in <module>
    from mixture_of_attention.rotary_emb import apply_rotary_pos_emb
ModuleNotFoundError: No module named 'mixture_of_attention.rotary_emb'

**Comment by lucidrains** [comment]
@puallee hey Travis, thanks for your interest

i forgot to check in that file! should be there now

**Comment by puallee** [comment]
please update it, thanks

**Comment by lucidrains** [comment]
should be there
